### ISSUE TITLE
Error when calling antenna methods

### ISSUE THREAD

**Issue by simonerom** [iotexproject/iotex-antenna#429]
I'm suddenly getting this error when calling antenna methods in nodejs:

```
 Error: 14 UNAVAILABLE: Trying to connect an http1.x server
    at Object.exports.createStatusError (/Users/simone/Source/GitHub/simonerom/iotexdelegate.com/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/simone/Source/GitHub/simonerom/iotexdelegate.com/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/simone/Source/GitHub/simonerom/iotexdelegate.com/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/simone/Source/GitHub/simonerom/iotexdelegate.com/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/simone/Source/GitHub/simonerom/iotexdelegate.com/node_modules/grpc/src/client_interceptors.js:847:24)
    at callbackTrampoline (internal/async_hooks.js:126:14) {code: 14, metadata: Metadata, details: 'Trying to connect an http1.x server', stack: 'Error: 14 UNAVAILABLE: Trying to connect an h…ckTrampoline (internal/async_hooks.js:126:14)', message: '14 UNAVAILABLE: Trying to connect an http1.x server'}
```
the code I'm using is
```js
const Antenna = require("iotex-antenna").default;

const antenna = new Antenna("api.mainnet.iotex.one:80");

let stats = await antenna.iotx.getChainMeta();
```

This used to work normally until a couple weeks ago, it stopped working without any intervention on my side (could it be due to the 1.8.4 update?)

**Comment by ququzone** [comment]
@simonerom You can change to the below endpoints
- `api.iotex.one:443`
- `api.mainnet.iotex.one:443`

Insecure endpoints will shut down gradually.

**Comment by simonerom** [comment]
@ququzone was this tested and working? 

I've tested both :80 and :443 and I have the same error regardless of using secure on non-secure endpoints.

**Comment by simonerom** [comment]
@ququzone FYI, I did one more test and the problem seems to be happening only with the official endpoints 
```
api.iotex.one:443 or :80
api.mainnet.iotex.one:443 or :80
```

my code is working if I point it to my own gateway `gateway.iotexlab.io:80`
